#! /bin/bash
######################################################################################
######################################################################################
###                     author: Sunny Adeola                                       ###
###                     email: osadeola@us.ibm.com                                 ###
###                     date: 01-07-2019                                           ###
### project: Module will clone existing repository                                 ###
### source: https://help.github.com/articles/cloning-a-repository/#platform-linux  ###
###                                                                                ###
###                                                                                ###
######################################################################################
######################################################################################
echo "Enter name github username:"
read Git_userName
echo "Enter gitgub repo name:"
read Git_repo

git clone https://github.com/$Git_userName/$Git_repo
